trigger:
  branches:
    include:
    - 'main'

variables:
- group: DevOps

resources:
  repositories:
    - repository: templates
      type: git
      name: Maski/Maski_DevOps
      ref: refs/heads/main

jobs:
- job: Build
  steps:
  - checkout: self
  # - task: vercel-deployment-task@1
  #   inputs:
  #     # condition: or(eq(variables.isMain, true), eq(variables['Build.Reason'], 'PullRequest'))
  #     vercelProjectId: 'prj_0avotsvXmY6a1dD4XqXWI4pkuZ0A'
  #     # vercelProjectId: 'azure-devops-extension'
  #     vercelOrgId: '4BJZDzrdJX1VxHC9u2lyXyFp'
  #     vercelToken: $(vercelPAT)
  #     production: true


  # - task: CmdLine@2
  #   displayName: Build phase
  #   inputs:
  #     script: |
  #       npm install
  #       npm run build
  
  - task: DownloadSecureFile@1
    displayName: Downloading .env
    inputs:
      secureFile: $(envFile)

  - script: mv "$(Agent.TempDirectory)/$(envFile)" "$(Build.SourcesDirectory)/.env"
    displayName: 'Rename env file'
  
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        ls -la
        ls -la $(Agent.TempDirectory)
  - task: CopyFiles@2
    inputs:
      SourceFolder: $(Agent.TempDirectory)
      Contents: ‘**\.env’
      TargetFolder: $(Build.SourcesDirectory)
      
  - template: Templates/DevSecOps/DockerScans.yml@templates

  








